site_name: Privacy audit
site_url: https://willingc.github.io/compliance-checker
theme:
  name: material
  features:
    - navigation.indexes

plugins:
  - glightbox:
      touchNavigation: false
      loop: false
      effect: zoom
      slide_effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
        - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: false
      manual: false

  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - index.md
  - 02-week1_use_cases.md
  - 03-week2_risk_model.md
  - 03-week2_use_cases_risks.md
  - 04-risks_01_models.md
  - 04-risks_02_access_control.md
  - 04-risks_03_telemetry.md
  - 04-risks_03_structured_logging.md
  - 04-risks_04_secrets_tokens_keys.md

