site_name: Privacy audit
site_url: https://willingc.github.io/compliance-checker
theme:
  name: material
  features:
    - navigation.indexes

plugins:
  - glightbox:
      width: 100%
      height: auto
      zoomable: true

  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - index.md
  - 02-week1_use_cases.md
  - 03-week2_risk_model.md
