[workspace]
authors = ["Carol Willing <carolcode@willingconsulting.com>"]
channels = ["conda-forge"]
name = "compliance-checker"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mkdocs-glightbox = ">=0.5.2,<0.6"
mkdocs-material = ">=9.7.6,<10"
