[workspace]
authors = ["Carol Willing <carolcode@willingconsulting.com>"]
channels = ["conda-forge"]
name = "compliance-checker"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
serve = "zensical serve"

[dependencies]
zensical = ">=0.0.40,<0.0.41"
